name: Bench

on: [push]

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    environment: meta-tracing-environment
    container:  
      image: iamkimchi/pypy-trace:latest
    steps:
    - uses: actions/checkout@v3
    - name: Download PyPy
      run: make get-pypy
    - name: lfs install
      run: git lfs install
    - name: lfs pull
      run: git lfs pull
    - name: Bench 0.0.4 [loops.ki]
      run: |
        hyperfine -m 100 -M 100 './bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-jit-c ./programs/loops.ki' \
         'bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-jit-c ./programs/loops.ki self-like'
    - name: Bench 0.0.4 [loops_recursive.ki]
      run: |
        hyperfine './bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-jit-c ./programs/loops_recursive.ki' \
         'bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-jit-c ./programs/loops_recursive.ki self-like'
