name: RPython Translate 

on: [push]

jobs:
  rpython-no-jit:
    name: PYPY translate (no jit)
    container: iamkimchi/pypy-trace:latest
    steps:
    - uses: actions/checkout@v3
    - name: Download PyPy
      run: make get-pypy
    - name: RPython Translate
      run: make ./scripts/translate_and_store.sh $(make version) ./src/main.py

