name: Test 

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:  
      image: iamkimchi/pypy-trace:latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Pypy
      run: make get-pypy
    - name: Test with pytest
      run: PYTHONPATH=${PWD}:${PWD}/.pypy/ && pytest ./src