name: Test 

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: interpreter-py
        environment-file: environment.yml
        python-version: 2.7.18
        auto-activate-base: false
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 ./src/**/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        # conda install pytest
        pip install rpython
        # pip install pytest
        # which rpython
        # which pytest
        # which py.test
        source .envrc && PYTHONPATH=${PWD}:${PWD}/src/:${PWD}/.pypy/ pytest ./src
